### ISSUE TITLE
Linting is being skipped

### ISSUE THREAD

**Issue by bobbywlindsey** [joenye/coc-cfn-lint#4]
Is there a reason why linting is skipping [this json file](https://github.com/bobbywlindsey/ml-model-lambda-microservice/blob/master/infrastructure/cloudformation.json)?

It contains `Resources` and I even tried adding `AWSTemplateFormatVersion` as well.

**Comment by joenye** [comment]
It skips because, by default, the file must contain `AWSTemplateFormatVersion` and `Resources`. 

Try adding this to your Coc settings:

```json
"cfnlint.detectCfnRegExps": ["\\n?\"Resources\"?\\s*:"],
```

**Comment by bobbywlindsey** [comment]
Awesome, that fixed it!
